
/*
 * Copyright (C) 2015 Instras Scientific LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.instras;

import com.phidget22.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import javax.swing.filechooser.FileSystemView;

/**
 * A simple program to control the SCK-300S+ spin coater kit
 * which uses the PhidgetStepper Bipolar HC (https://www.phidgets.com/?tier=3&catid=23&pcid=20&prodid=66)
 * @author Nathan Stevens
 * @version 2.0 11/17/2020
 */
public class SCKTalkPhiDesktop extends javax.swing.JFrame {
    // this object handle talking to the motor control board
    private Stepper stepperPhidget;
        
    // The spin speed to set
    private int setSpeed = 0;
    
    // used to move the motor in correct direction 1 = CW, -1 = CCW
    private int direction = 1;
    
    // the time object for count seconds
    private Timer spinTimer = null;
    
    // keep track of the spin time
    private int spinTime = 0;
    private int targetSpinTime = 0;
    
    // used to exit the ramp sequence thread if the stop button was pressed
    private boolean stopMotor;
        
    /**
     * Creates new form SCKTalkPhiMain
     */
    public SCKTalkPhiDesktop() {
        initComponents();
        
        // set the title of the frame now
        setTitle(SCKTalkPhi.VERSION);
        
        // set the scaling factor
        rescaleFactorTextField.setText("" + SCKTalkPhi.SCALE_FACTOR);
        
        // read the save data from text field
        readSavedStepSequence();
        
        // create a timer object for count seconds the motor is spining
        spinTimer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                updateSpinTime();
            }
        });
        
        // add window listener so that we deactivate the motor when 
        // the window is closed
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                exitButtonActionPerformed(null);
            }
        });
    }
    
    /**
     * Method to read the saved step sequence data
     */
    private void readSavedStepSequence() {
        String filePath = System.getProperty("user.dir") + File.separator + SCKTalkPhi.RAMP_SEQUENCE_FILE;
        String stepSequence = SCKTalkPhi.readFileAsString(filePath);
        
        if(stepSequence !=null) {
             rampProgramTextArea.setText(stepSequence);
        }
    }
    
    /**
     * Method to save the step sequence
     * @param filePath 
     */
    private void saveStepSequence(String filePath) {
        if(filePath == null) {
            filePath = System.getProperty("user.dir") + File.separator + SCKTalkPhi.RAMP_SEQUENCE_FILE;
        }
        
        String content = rampProgramTextArea.getText();
        SCKTalkPhi.writeStringToFile(content, filePath);
    }
    
    /**
     * Method to update the spin time or stop the motor from spinning
     */
    private void updateSpinTime() {
        spinTime++;
        
        // check to see if spin time is not more that the target time
        // if it is then stop the motor
        if(targetSpinTime > 0 && spinTime > targetSpinTime) {
            stopButtonActionPerformed(null);
        } else {
            spinTimeLabel.setText(spinTime + " sec");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spinSpeedTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        runRampSequenceCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        incrementComboBox = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        accelarationTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        currentLimitTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rescaleFactorTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        directionComboBox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        maxSpinSpeedTextField = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        connectLabel = new javax.swing.JLabel();
        spinSpeedLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        spinTimeTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        rampProgramTextArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        spinTimeLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rampStepTextField = new javax.swing.JTextField();
        saveRampButton = new javax.swing.JButton();
        loadRampButton = new javax.swing.JButton();

        jLabel14.setText("Max Speed");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SCKTalkPhi");

        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        startButton.setText("START");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        upButton.setText("  UP  ");
        upButton.setToolTipText("");
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });

        downButton.setText("DOWN");
        downButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtonActionPerformed(evt);
            }
        });

        stopButton.setText("STOP");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Spin Speed");
        jLabel1.setToolTipText("");

        spinSpeedTextField.setText("3000");
        spinSpeedTextField.setToolTipText("");
        spinSpeedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spinSpeedTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Set Speed (rpm)");

        runRampSequenceCheckBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        runRampSequenceCheckBox.setForeground(java.awt.Color.blue);
        runRampSequenceCheckBox.setText("Run Ramp Sequence");
        runRampSequenceCheckBox.setToolTipText("");
        runRampSequenceCheckBox.setActionCommand("");

        jLabel3.setText("Step Increment (rpm)");
        jLabel3.setToolTipText("");

        incrementComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "10", "20", "50", "100" }));
        incrementComboBox.setSelectedIndex(1);
        incrementComboBox.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Advance Settings"));

        jLabel4.setText("Accelaration (rpms/s)");

        accelarationTextField.setText("1500");
        accelarationTextField.setToolTipText("");
        accelarationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accelarationTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Current Limit (A)");

        currentLimitTextField.setText("1.0");
        currentLimitTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentLimitTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Rescale Factor");
        jLabel6.setToolTipText("");

        rescaleFactorTextField.setText("0.000");
        rescaleFactorTextField.setToolTipText("");
        rescaleFactorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rescaleFactorTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Rotation");
        jLabel8.setToolTipText("");

        directionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Clockwise", "Counter Clockwise" }));
        directionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directionComboBoxActionPerformed(evt);
            }
        });

        jLabel15.setText("Max Speed (rpms)");

        maxSpinSpeedTextField.setEditable(false);
        maxSpinSpeedTextField.setText("9000");
        maxSpinSpeedTextField.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accelarationTextField)
                    .addComponent(currentLimitTextField)
                    .addComponent(rescaleFactorTextField)
                    .addComponent(directionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxSpinSpeedTextField)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(accelarationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(currentLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(rescaleFactorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(maxSpinSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(directionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        connectLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        connectLabel.setForeground(java.awt.Color.red);
        connectLabel.setText("Not Connected");

        spinSpeedLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        spinSpeedLabel.setForeground(new java.awt.Color(0, 51, 255));
        spinSpeedLabel.setText("0");

        jLabel11.setText("Spin Time (s)");

        spinTimeTextField.setText("0");
        spinTimeTextField.setToolTipText("");
        spinTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spinTimeTextFieldActionPerformed(evt);
            }
        });

        rampProgramTextArea.setColumns(20);
        rampProgramTextArea.setRows(5);
        rampProgramTextArea.setText("STEP #, RPM, Dwell Time (s)\n1, 500, 25\n2, 3500, 30\n3, 1000, 15\n4, 0, 10\n5, 3250, 20");
        jScrollPane2.setViewportView(rampProgramTextArea);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Spin Time");

        spinTimeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        spinTimeLabel.setForeground(java.awt.Color.blue);
        spinTimeLabel.setText("0");

        jLabel16.setText("Ramp Step");

        rampStepTextField.setEditable(false);
        rampStepTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rampStepTextField.setForeground(java.awt.Color.blue);
        rampStepTextField.setText("Program Not Running ..");
        rampStepTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rampStepTextFieldActionPerformed(evt);
            }
        });

        saveRampButton.setText("SAVE");
        saveRampButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRampButtonActionPerformed(evt);
            }
        });

        loadRampButton.setText("LOAD");
        loadRampButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadRampButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spinSpeedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spinTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(connectButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(connectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(spinSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(incrementComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 13, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(runRampSequenceCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rampStepTextField)
                                    .addComponent(spinTimeTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveRampButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loadRampButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upButton)
                        .addGap(8, 8, 8)
                        .addComponent(downButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runRampSequenceCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectButton)
                    .addComponent(connectLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(spinSpeedLabel)))
                    .addComponent(jScrollPane2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(spinTimeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(incrementComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(rampStepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(spinSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(spinTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exitButton)
                            .addComponent(stopButton)
                            .addComponent(downButton)
                            .addComponent(upButton)
                            .addComponent(startButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveRampButton)
                            .addComponent(loadRampButton))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Method to start the motor turning
     * 
     * @param evt 
     */
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if(stepperPhidget == null) {
            JOptionPane.showMessageDialog(this,
                "The SCK-300S+ is not connected ...",
                "Connection Error",
                JOptionPane.ERROR_MESSAGE);
            
            return;
        }
        
        try {
            startButton.setEnabled(false);
            
            //Set up some initial acceleration and velocity values
            Double accleration = Double.valueOf(accelarationTextField.getText());
            stepperPhidget.setAcceleration(accleration);
            
            // set the current limit
            stepperPhidget.setCurrentLimit(Double.parseDouble(currentLimitTextField.getText()));
                       
            // set the spin time
            spinTimeTextFieldActionPerformed(null);
            
            // power-up the motor now
            System.out.println("\nEngaging Stepper Motor\n");
            stepperPhidget.setEngaged(true);
            
            if(runRampSequenceCheckBox.isSelected()) {
                // start a step seqence
                startStepSequence();
            } else {
                // start the timer
                spinTimer.start();
            
                // set the speed now
                spinSpeedTextFieldActionPerformed(null);
            }
        } catch (PhidgetException ex) {
            Logger.getLogger(SCKTalkPhiDesktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startButtonActionPerformed
    
    /**
     * Method to run the step sequence the step sequence
     */
    private void startStepSequence() {
        // check that the sequence is good
        final String[] stepSeqences = checkStepSequences();
        if(stepSeqences == null) { 
            stopButtonActionPerformed(null);
            return; 
        }
        
        // create a swing work to run the sequence in the background
        SwingWorker worker = new SwingWorker<Boolean, Void>() {
            @Override
            public Boolean doInBackground() {
                stopMotor = false;
                
                // interate over the lines containing the seqences
                for(int i = 1; i < stepSeqences.length; i++) {
                    String[] stepInfo = stepSeqences[i].split("\\s*,\\s*");
                    String setSpeedString = stepInfo[1].trim();
                    targetSpinTime = Integer.parseInt(stepInfo[2].trim());
                    
                    rampStepTextField.setText(stepInfo[0] + ", " + setSpeedString + " rpms, " + targetSpinTime + " sec");
                    
                    // start the motor spinning
                    spinSpeedTextField.setText(setSpeedString);
                    spinSpeedTextFieldActionPerformed(null);
                    
                    // use a loop to keep track of time this step is running
                    int count = 0;
                    while(count < targetSpinTime) {
                        // check to if the motor was stop
                        if(stopMotor) {
                            rampStepTextField.setText("Sequenced Stopped ...");
                            return false;
                        }
                        
                        // update the count timer
                        spinTimeLabel.setText("" + (targetSpinTime - count));
                        
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(SCKTalkPhiDesktop.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                        count++;
                    }
                }
                
                // stop the motor now
                stopButtonActionPerformed(null);
                
                // seqeunce complete so return true
                return true;
            }
        };
        
        worker.execute();
    }
    
    /**
     * Check that the step sequence has no errors
     * 
     * @return a string array containing the step sequence  
     */
    private String[] checkStepSequences() {
        String[] stepSeqences = rampProgramTextArea.getText().split("\n");

        // interate over the lines containing the seqences
        for (int i = 1; i < stepSeqences.length; i++) {
            String[] stepInfo = stepSeqences[i].split("\\s*,\\s*");
            String step = stepInfo[0].trim();
            
            try {
                int speed = Integer.parseInt(stepInfo[1].trim());
                int time = Integer.parseInt(stepInfo[2].trim());

                System.out.println("Checked: " + step + ", " + speed + " rpms, " + time + " sec");
            } catch(NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this,
                    "There is an error in step sequence #" + step + ". Please dobule check ...",
                    "Step Sequence Error",
                    JOptionPane.ERROR_MESSAGE);
                
                stepSeqences = null;
                break;
            }
        }
        
        return stepSeqences;
    }
    
    /**
     * Exit the program
     * @param evt 
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        if(stepperPhidget != null) {
            try {
                stepperPhidget.setEngaged(false);
                stepperPhidget.close();
            } catch (PhidgetException ex) {
                Logger.getLogger(SCKTalkPhiDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        // save the step sequence
        saveStepSequence(null);
        
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
    
    /**
     * Connect to the stepper phidget board
     * 
     * @param evt 
     */
    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        if(stepperPhidget != null) {
            return;
        }
        try {
            stepperPhidget = new Stepper();
            
            System.out.println("Waiting for the Phidget Stepper to be attached...\n");
            stepperPhidget.open(Phidget.DEFAULT_TIMEOUT);
            
            // set the scaling factor and control mode to RUN 
            // so we are in continous rotation mode
            double rescaleFactor = Double.parseDouble(rescaleFactorTextField.getText());
            stepperPhidget.setRescaleFactor(rescaleFactor);
            stepperPhidget.setControlMode(StepperControlMode.RUN);
            
            System.out.println("Phidget Information");
            System.out.println("================================================");
            System.out.println("Version: " + stepperPhidget.getDeviceVersion());
            System.out.println("Name: " + stepperPhidget.getDeviceName());
            System.out.println("Serial #: " + stepperPhidget.getDeviceSerialNumber());
            
            // update the UI label to indicate successful connection
            connectLabel.setForeground(new Color(0x00, 0xC0, 0x00));
            connectLabel.setText("Connected to SCK-300S+");
            
            // add some listeners now
            stepperPhidget.addErrorListener(new ErrorListener() {
                public void onError(ErrorEvent ex) {
                    connectLabel.setText("Connection Failed ...");
                    System.out.println("\n--->Error: " + ex.getDescription());
                }
            });
            
            // listener which displays the current rpm
            stepperPhidget.addVelocityChangeListener(new StepperVelocityChangeListener() {
                @Override
                public void onVelocityChange(StepperVelocityChangeEvent svce) {
                    long speed = Math.round(svce.getVelocity());
                    spinSpeedLabel.setText(speed + " rpms");
                }
            });
        } catch (PhidgetException ex) {
            JOptionPane.showMessageDialog(this,
            "Stepper Driver Not Found",
            "Connection Error", JOptionPane.ERROR_MESSAGE);
            
            connectLabel.setText("Connection Failed ...");
            Logger.getLogger(SCKTalkPhiDesktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_connectButtonActionPerformed
    
    /**
     * Set the current motor speed
     * 
     * @param evt 
     */
    private void spinSpeedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spinSpeedTextFieldActionPerformed
        try {
            int changeBy = 100; // how much to change the speed when reducing speed
             
            int newSpeed = Integer.parseInt(spinSpeedTextField.getText());
            
            if(newSpeed >= setSpeed) {
                setSpeed = newSpeed;
                setMotorSpeed();
            } else {
                // we need to decrease in steps of 100 rpms to prevent motor 
                // from lossing steps and stopping
                int diff = setSpeed - newSpeed;
                while (setSpeed > newSpeed && diff > changeBy) {
                    setSpeed -= changeBy;
                    setMotorSpeed();
                    
                    // pause a bit before decrease the speed again
                    Thread.sleep(25);
                }
                
                setSpeed = newSpeed;
                setMotorSpeed();
            }
            
            /**
            if(newSpeed >= setSpeed) {
                // we need to increase in steps of 100 rpms
                int diff = newSpeed - setSpeed;
                while (setSpeed < newSpeed && setSpeed != 0 && diff > changeBy*10) {
                    setSpeed += changeBy*2;
                    setMotorSpeed();
                    
                    // pause a bit before increasing speed again
                    Thread.sleep(50);
                }
                
                if(setSpeed != newSpeed) {
                    setSpeed = newSpeed;
                    setMotorSpeed();
                }
            } else {
                changeBy = changeBy/2;
                
                // we need to decrease in steps of 50 rpms
                int diff = setSpeed - newSpeed;
                while (setSpeed > newSpeed && diff > changeBy) {
                    setSpeed -= changeBy;
                    setMotorSpeed();
                    
                    // pause a bit before decrease the speed again
                    Thread.sleep(25);
                }
                
                setSpeed = newSpeed;
                setMotorSpeed();
            }
            */
        } catch(NumberFormatException | InterruptedException ex) {
            Logger.getLogger(SCKTalkPhiDesktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_spinSpeedTextFieldActionPerformed
    
    /**
     * Stop the motor
     * @param evt 
     */
    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        stopMotor = true;
        
        try {
            if(stepperPhidget != null) {
                stepperPhidget.setEngaged(false);
            }
            
            spinTimer.stop();
            spinTime = 0;
            setSpeed = 0;
            
            spinSpeedLabel.setText("stopped");
            spinTimeLabel.setText("0");
            startButton.setEnabled(true);
        } catch (PhidgetException ex) {
            Logger.getLogger(SCKTalkPhiDesktop.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_stopButtonActionPerformed

    /**
     * The UP button was pressed so increment the current speed
     * 
     * @param evt 
     */
    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
        int increment = Integer.parseInt(incrementComboBox.getSelectedItem().toString());
        
        // if the set speed is zero, let's from the TF
        if(setSpeed == 0) {
            setSpeed = Integer.parseInt(spinSpeedTextField.getText());
        }
        
        setSpeed += increment;
        
        // update the UI and set the motor speed
        spinSpeedTextField.setText(""+ setSpeed);
        
        setMotorSpeed();
    }//GEN-LAST:event_upButtonActionPerformed
    
    /**
     * The DOWN button was pressed so reduce the speed
     * 
     * @param evt 
     */
    private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButtonActionPerformed
        int increment = Integer.parseInt(incrementComboBox.getSelectedItem().toString());
        setSpeed -= increment;
        
        if(setSpeed < 0) {
            setSpeed = 0;
        }
        
        // update the UI and set the motor speed
        spinSpeedTextField.setText(""+ setSpeed);
        
        setMotorSpeed();
    }//GEN-LAST:event_downButtonActionPerformed
    
    /**
     * Set the current sent to the motor
     * 
     * @param evt 
     */
    private void currentLimitTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentLimitTextFieldActionPerformed
        if(stepperPhidget == null) return;
        
        try {
            double current = Double.parseDouble(currentLimitTextField.getText());
            System.out.println("Setting Current To: " + current);
            stepperPhidget.setCurrentLimit(current);
        } catch (PhidgetException ex) {
            Logger.getLogger(SCKTalkPhiDesktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_currentLimitTextFieldActionPerformed
    
    /**
     * Set the target time
     * 
     * @param evt 
     */
    private void spinTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spinTimeTextFieldActionPerformed
        try {
            targetSpinTime = Integer.parseInt(spinTimeTextField.getText());
            System.out.println("Target Spin Time: " + targetSpinTime);
        } catch(NumberFormatException nfe) {}
    }//GEN-LAST:event_spinTimeTextFieldActionPerformed
    
    /**
     * Used to set the direction of rotation
     * @param evt 
     */
    private void directionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directionComboBoxActionPerformed
        if(directionComboBox.getSelectedIndex() == 0) {
            direction = 1;
        } else {
            direction = -1;
        }
    }//GEN-LAST:event_directionComboBoxActionPerformed
    
    /**
     * Start the step sequence. This is just for testing
     * @param evt 
     */
    private void rampStepTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rampStepTextFieldActionPerformed
        startStepSequence();
    }//GEN-LAST:event_rampStepTextFieldActionPerformed

    private void accelarationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accelarationTextFieldActionPerformed
        if(stepperPhidget == null) return;
        
        try {
            Double accleration = Double.valueOf(accelarationTextField.getText());
            stepperPhidget.setAcceleration(accleration);
        } catch (PhidgetException ex) {
            Logger.getLogger(SCKTalkPhiDesktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_accelarationTextFieldActionPerformed

    private void rescaleFactorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rescaleFactorTextFieldActionPerformed
        if(stepperPhidget == null) return;
        
        try {
            double rescaleFactor = Double.parseDouble(rescaleFactorTextField.getText());
            stepperPhidget.setRescaleFactor(rescaleFactor);
        } catch (PhidgetException ex) {
            Logger.getLogger(SCKTalkPhiDesktop.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rescaleFactorTextFieldActionPerformed

    private void saveRampButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRampButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = fileChooser.showSaveDialog(this);
 
        // if the user selects a file
        if (r == JFileChooser.APPROVE_OPTION) {
            // get the path of the selected file
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            String content = rampProgramTextArea.getText();
            SCKTalkPhi.writeStringToFile(content, filePath);
        }
    }//GEN-LAST:event_saveRampButtonActionPerformed

    private void loadRampButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadRampButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int r = fileChooser.showOpenDialog(this);
 
        // if the user selects a file
        if (r == JFileChooser.APPROVE_OPTION) {
            // get the path of the selected file
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            String content = SCKTalkPhi.readFileAsString(filePath);
            rampProgramTextArea.setText(content);
        }
    }//GEN-LAST:event_loadRampButtonActionPerformed
    
    /**
     * Given an RPM reading set the speed by converting to micro-steps per second
     */
    public void setMotorSpeed() {
        //double rps = setSpeed/60.0; // rounds per second 
        //double sps = rps*96.0;      // steps per second 
        //long msps = (long)sps*16;   // get the microsteps per second needed
        
        System.out.println("Set RPM: " + setSpeed);
        
        if(stepperPhidget != null) {
            try {
                if(setSpeed == 0) {
                    // disencage the motor and encage it again to fix bug
                    stepperPhidget.setVelocityLimit(setSpeed);
                    stepperPhidget.setEngaged(false);
                    Thread.sleep(50);
                    stepperPhidget.setEngaged(true);
                }
                else {
                    double speed = direction*setSpeed;
                    stepperPhidget.setVelocityLimit(speed);
                }
            } catch (PhidgetException | InterruptedException ex) {
                Logger.getLogger(SCKTalkPhiDesktop.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accelarationTextField;
    private javax.swing.JButton connectButton;
    private javax.swing.JLabel connectLabel;
    private javax.swing.JTextField currentLimitTextField;
    private javax.swing.JComboBox directionComboBox;
    private javax.swing.JButton downButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JComboBox incrementComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadRampButton;
    private javax.swing.JTextField maxSpinSpeedTextField;
    private javax.swing.JTextArea rampProgramTextArea;
    private javax.swing.JTextField rampStepTextField;
    private javax.swing.JTextField rescaleFactorTextField;
    private javax.swing.JCheckBox runRampSequenceCheckBox;
    private javax.swing.JButton saveRampButton;
    private javax.swing.JLabel spinSpeedLabel;
    private javax.swing.JTextField spinSpeedTextField;
    private javax.swing.JLabel spinTimeLabel;
    private javax.swing.JTextField spinTimeTextField;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables
}
